#!/usr/bin/env bash

source "${HOME}/.cache/wal/colors.sh"

echo "
* {
    background:                     $color0;
    background-alt:                 $color0;
    foreground:                     $color7;
    border:                         $color0;
    border-alt:                     $color0;
    selected:                       $color10;
    urgent:                         $color9;
}
"
